### PR TITLE
Fixed warnings produced by client codegen under Scala 3.7

### LINKED ISSUE #2687: Generated code for client produces warning under Scala 3.7.x
The generated code for client contains implicits passed explicitly which now requires the `using` keyword from Scala 3.7.0 or a warning is triggered. Unfortunately we can't just add that because then the code will not compile under older Scala versions. It seems we need something like the `scala3_sources` in ScalaPB. See similar workaround: https://github.com/scalapb/ScalaPB/pull/1854

### PR DESCRIPTION
**Pull request by ghostdogpr**
Closes #2687

### CODE REVIEW

File: tools/src/main/scala/caliban/tools/ClientWriter.scala [hunk 1]
```diff
@@ -235,16 +235,20 @@ object ClientWriter {
       val argBuilder                                       = filteredArgs match {
         case Nil  => ""
         case list =>
-          s", arguments = List(${list.zipWithIndex.map { case (arg, idx) =>
-              s"""Argument("${arg.name}", ${safeName(arg.name)}, "${arg.ofType.toString}")(encoder$idx)"""
```
Comment (ghostdogpr) [inline tools/src/main/scala/caliban/tools/ClientWriter.scala:239]: Stop passing implicits explicitly

File: tools/src/main/scala/caliban/tools/ClientWriter.scala [hunk 2]
```diff
@@ -235,16 +235,20 @@ object ClientWriter {
...
             }.mkString(", ")})"
       }
       val implicits                                        = filteredArgs match {
         case Nil  => ""
         case list =>
-          s"(implicit ${list.zipWithIndex.map { case (arg, idx) =>
-              s"""encoder$idx: ArgEncoder[${writeType(arg.ofType)}]"""
-            }.mkString(", ")})"
+          s"(implicit ${list
+              .distinctBy(_.ofType)
```
Comment (ghostdogpr) [inline tools/src/main/scala/caliban/tools/ClientWriter.scala:246]: In case 2 parameters have the same type.
