### PR TITLE
Fix description of temporal schemas

### LINKED ISSUE #822: Incorrectly rendered description for ZonedDateTime
Hi,

When I use a `ZonedDateTime` in my schema I get the following description for it when it is rendered:
```
"A date-time with a time-zone in the ISO-8601 calendar system using the format (ParseCaseSensitive(false)(ParseCaseSensitive(false)(Value(Year,4,10,EXCEEDS_PAD)'-'Value(MonthOfYear,2)'-'Value(DayOfMonth,2))'T'(Value(HourOfDay,2)':'Value(MinuteOfHour,2)[':'Value(SecondOfMinute,2)[Fraction(NanoOfSecond,0,9,DecimalPoint)]]))ParseStrict(false)Offset(+HH:MM:ss,'Z')ParseStrict(true))['['ParseCaseSensitive(true)ZoneRegionId()']']"
scalar ZonedDateTime
```

### PR DESCRIPTION
**Pull request by ghostdogpr**
Closes #822

### CODE REVIEW

File: core/src/main/scala/caliban/schema/Schema.scala [hunk 1]
```diff
@@ -500,7 +502,9 @@ trait TemporalSchema {
   def localDateTimeSchemaWithFormatter(formatter: DateTimeFormatter): Schema[Any, LocalDateTime] =
     temporalSchemaWithFormatter(
       "LocalDateTime",
-      Some(s"A date-time without a time-zone in the ISO-8601 calendar system in the format of $formatter")
+      Some(
+        s"A date-time without a time-zone in the ISO-8601 calendar system in the format of ${formatter.format(sampleDate)}"
```
Comment (paulpdaniels) [inline core/src/main/scala/caliban/schema/Schema.scala:506]: Clever! 🥇

**Review by paulpdaniels — APPROVED** [review]

File: core/src/main/scala/caliban/schema/Schema.scala [hunk 2]
```diff
@@ -471,6 +471,8 @@ trait TemporalSchema {
       PureStep(format(value))
   }
 
+  lazy val sampleDate: ZonedDateTime = ZonedDateTime.ofInstant(Instant.EPOCH, ZoneId.systemDefault())
```
Comment (paulpdaniels) [inline core/src/main/scala/caliban/schema/Schema.scala:474]: I think we should use the `ZoneOffset.UTC` instead of `systemDefault()` here since it may result in different behaviors in two schemas generated on different computers.

Comment (ghostdogpr) [reply core/src/main/scala/caliban/schema/Schema.scala]: Good point, I changed.
