### PR TITLE
Fix validation for lists containing `oneOf` inputs

### LINKED ISSUE #2603: Cannot run mutation that has `oneOf` input objects inside a list
```scala
test("oneOf input inside array") {

  case class AddPets(pets: List[Pet.Wrapper])
  case class Queries(addPets: AddPets => List[Pet])

  val api: GraphQL[Any] = graphQL(
    RootResolver(
      Queries(_.pets.map(_.pet))
    )
  )

  val cases = List(
    gqldoc("""{
      addPets(pets: [
        { cat: { name: "a" } },
        { dog: { name: "b" } }
      ]) {
        __typename
        ... on Cat { name }
        ... on Dog { name }
      }
    }""") -> """{"addPets":[{"__typename":"Cat","name":"a"},{"__typename":"Dog","name":"b"}]}"""
  )

  ZIO.foldLeft(cases)(assertCompletes) { case (acc, (query, expected)) =>
    api.interpreter
      .flatMap(_.execute(query))
      .map(response => acc && assertTrue(response.data.toString == expected))
  }
}
```

Fails with `Argument 'pets' on field 'addPets' is not a valid OneOf Input Object` due to https://github.com/ghostdogpr/caliban/blob/v2.10.0/core/src/main/scala/caliban/validation/Validator.scala#L594 returning true for a list that contains input objects.

### PR DESCRIPTION
**Pull request by guymers**
/fixes #2603

### CODE REVIEW

**Comment by ghostdogpr** [comment]
The mima failure is very weird, it's comparing against an old version 🤔

**Comment by guymers** [comment]
Looks like it was using the latest tag that was in my fork, I pushed 2.10.0 to it, passing now.

**Review by ghostdogpr — APPROVED** [review]
LGTM

@kyri-petrou do you wanna take a look since you added `oneOf` in the first place?

File: core/src/main/scala/caliban/validation/ValueValidator.scala [hunk 1]
```diff
@@ -79,14 +79,28 @@ private object ValueValidator {
...
+                    "OneOf Input Object arguments must specify exactly one non-null key"
+                  )
+                } else if (
+                  inputType._isOneOfInput && fields.size == 1 && fields.headOption.map(_._2).contains(NullValue)
+                ) {
+                  failValidation(
+                    s"$errorContext is not a valid OneOf Input Object",
+                    "OneOf Input Object arguments must specify exactly one non-null key"
+                  )
+                } else {
```
Comment (kyri-petrou) [inline core/src/main/scala/caliban/validation/ValueValidator.scala]: Can't we make `Validator.validateOneOfInputValue` package-private (within `validation`) and reuse it here?

Comment (guymers) [reply core/src/main/scala/caliban/validation/ValueValidator.scala]: Done
