### PR TITLE
Fix ArgBuilder derivation for case classes containing only optional fields

### LINKED ISSUE #2407: Incorrect behaviour of `ArgBuilder` containing only nullable fields when input is null
Given the following case class:

```scala
case class Foo(value1: Option[String], value2: Option[String]) derives ArgBuilder
```

I expect that the derived `ArgBuilder#build` should work in the following ways:
1. Input: `{}`, output: `Right(Foo(None, None))`
2. Input: `null`, output `Left(ExecutionError("bla"))`

However, currently both cases succeed with `Foo(None, None)`. Can be reproduced with the following test that should pass but fails since the first condition is not `Left`

```scala
    suite("derived build")(
      test("should fail when null is provided for case class with optional fields") {
        case class Foo(value: Option[String])
        val ab = ArgBuilder.gen[Foo]
        assertTrue(
          ab.build(NullValue).isLeft,
          ab.build(ObjectValue(Map())).isRight
        )
      }
    )
```

PS: This is not a problem when validation is enabled as an error will be raised during the validation phase

### PR DESCRIPTION
**Pull request by kyri-petrou**
/fixes #2407

Issue was that we were treating all case classes as potential value types. Fix is to determine during compile-time whether the case class is a value type (either using annotations or checking if the case class extends `AnyVal`)

@guymers I also added the tests that were in #2403 to ensure that `oneOf` input derivation is working as expected now.

### CODE REVIEW

File: core/src/main/scala-2/caliban/schema/ArgBuilderDerivation.scala [hunk 1]
```diff
@@ -40,14 +39,18 @@ trait CommonArgBuilderDerivation {
...
+
     override private[schema] val partial: PartialFunction[InputValue, Either[ExecutionError, T]] = {
       case InputValue.ObjectValue(fields) if required.forall(fields.contains) => fromFields(fields)
     }
 
     def build(input: InputValue): Either[ExecutionError, T] =
       input match {
         case InputValue.ObjectValue(fields) => fromFields(fields)
-        case value                          => ctx.constructMonadic(p => p.typeclass.build(value))
+        case value if isValueType           => ctx.constructMonadic(p => p.typeclass.build(value))
```
Comment (kyri-petrou) [inline core/src/main/scala-2/caliban/schema/ArgBuilderDerivation.scala]: @ghostdogpr do you recon we should change the line above to `case InputValue.ObjectValue(fields) if !isValueType` as well? Or are we risking to create issues with edge cases?

File: core/src/main/scala-2/caliban/schema/ArgBuilderDerivation.scala [hunk 2]
```diff
@@ -40,14 +39,18 @@ trait CommonArgBuilderDerivation {
...
+        case _                              => Left(ExecutionError("expected an input object"))
```
Comment (ghostdogpr) [inline core/src/main/scala-2/caliban/schema/ArgBuilderDerivation.scala]:
```suggestion
        case _                              => Left(ExecutionError("Expected an input object"))
```

File: core/src/main/scala-2/caliban/schema/ArgBuilderDerivation.scala (hunk 1 above)
Comment (ghostdogpr) [reply core/src/main/scala-2/caliban/schema/ArgBuilderDerivation.scala]: Do you mean the line below? I think it's okay to fail 🤔

File: core/src/main/scala-3/caliban/schema/ArgBuilderDerivation.scala [hunk 3]
```diff
@@ -143,7 +153,8 @@ trait CommonArgBuilderDerivation {
     def build(input: InputValue): Either[ExecutionError, A] =
       input match {
         case InputValue.ObjectValue(fields) => fromFields(fields)
-        case value                          => fromValue(value)
+        case value if isValueType           => fromValue(value)
+        case _                              => Left(ExecutionError("expected an input object"))
```
Comment (ghostdogpr) [inline core/src/main/scala-3/caliban/schema/ArgBuilderDerivation.scala]:
```suggestion
        case _                              => Left(ExecutionError("Expected an input object"))
```

File: core/src/main/scala-2/caliban/schema/ArgBuilderDerivation.scala (hunk 1 above)
Comment (kyri-petrou) [reply core/src/main/scala-2/caliban/schema/ArgBuilderDerivation.scala]: No I mean the line above (i.e., `case InputValue.ObjectValue(fields) => fromFields(fields)`). I'm wondering whether it should be changed to:

```scala
case InputValue.ObjectValue(fields) if !isValueType => fromFields(fields)
```

A case where this can be "problematic" is this:

```scala
        @GQLValueType
        case class Foo(value: Option[String])

        val ab = ArgBuilder.gen[Foo]
        assertTrue(
          ab.build(ObjectValue(Map())).isLeft
        )
```
Currently this test fails because `Map()` is a valid value if `Foo` wasn't a value type, but since it is a value type it should fail as `{}` is not a valid input for `Option[String]`

Comment (ghostdogpr) [reply core/src/main/scala-2/caliban/schema/ArgBuilderDerivation.scala]: Yeah I think it makes sense to change as you suggested.

**Comment by kyri-petrou** [comment]
@ghostdogpr I noticed that we had some very similar logic for determining value types in SchemaDerivation. In order to avoid conflicts, I reused the same logic for both deriving schemas & arg builders

**Review by ghostdogpr — APPROVED** [review]
