### PR TITLE
Fix incorrect description in interface server code gen

### LINKED ISSUE #1999: Codegen: Incorrect order of description in server sealed trait generation
I noticed a codegen problem when the result is a sealed trait:

```graphql
"""TypeNameDescription"""
interface TypeName {
  """fooDescription"""
  foo: AType!
}
```

```scala
@GQLInterface
@GQLDescription("traitDescription")
sealed trait TypeName extends scala.Product with scala.Serializable  {
         def @GQLDescription("description") foo : AType
}
```

And

```scala
def @GQLDescription("description") foo : AType
```
Isn't valid scala and should be : 

```scala
@GQLDescription("description") def status : AType
```

I suspect the problem comes from : https://github.com/ghostdogpr/caliban/blob/2a2479a4647eef592203df1538094a8d7deb84c9/tools/src/main/scala/caliban/tools/SchemaWriter.scala#L116

I can solve this but I'm afraid I don't know what is the correct way relatively to the rest of the codebase.

### PR DESCRIPTION
**Pull request by ghostdogpr**
Closes #1999

### CODE REVIEW

File: tools/src/test/scala/caliban/tools/SchemaWriterSpec.scala [hunk 1]
```diff
@@ -721,6 +721,7 @@ object SchemaWriterSpec extends ZIOSpecDefault {
         |  sealed trait AllErrors extends scala.Product with scala.Serializable derives caliban.schema.Schema.SemiAuto
         |  @GQLInterface
         |  sealed trait Error extends scala.Product with scala.Serializable derives caliban.schema.Schema.SemiAuto {
```
Comment (kyri-petrou) [inline tools/src/test/scala/caliban/tools/SchemaWriterSpec.scala:723]: As a side note, in Scala 3 we probably don't need the `extends scala.Product with scala.Serializable`. We can perhaps look into removing at some other time

**Review by kyri-petrou — APPROVED** [review]
