### PR TITLE
Fix nested type name computation

### LINKED ISSUE #425: Schema derivation doesn't handle nested types
Hello there, as already discussed in Discord, opening the issue here:
```
@ final case class ApiTranslated[T](value: T )
defined class ApiTranslated

@ case class Data2(a: ApiTranslated[Option[Double]], b: ApiTranslated[Option[Int]])
defined class Data2

@ val data2 = Data2(ApiTranslated(Some(1.0)), ApiTranslated(Some(5)))
data2: Data2 = Data2(ApiTranslated(Some(1.0)), ApiTranslated(Some(5)))

@ GraphQL.graphQL(RootResolver(data2))
res44: GraphQL[Any] = caliban.GraphQL$$anon$5@1ef8f1ca

@ res44.render
res45: String = """schema {
  query: Data2
}

type ApiTranslatedOption {
  value: Float
}

type Data2 {
  a: ApiTranslatedOption!
  b: ApiTranslatedOption!
}
```

Second field's(`Data2.b`) type is ApiTranslated[Option[Int]] but it's mapped to Float in schema

### PR DESCRIPTION
**Pull request by kiranbayram**
Closes #425

### CODE REVIEW

**Comment by kiranbayram** [comment]
Gave this a go @ghostdogpr It seems to be working according to the test i added but couldn't make the function tail recursive at this moment

File: core/src/main/scala/caliban/schema/Schema.scala [hunk 1]
```diff
@@ -452,8 +452,12 @@ trait DerivationSchema[R] {
     getDirectives(ctx.annotations)
 
   private def getName(annotations: Seq[Any], typeName: TypeName): String =
-    annotations.collectFirst { case GQLName(name) => name }
-      .getOrElse(typeName.short + typeName.typeArguments.map(_.short).mkString)
+    annotations.collectFirst { case GQLName(name) => name }.getOrElse {
+      typeName.typeArguments match {
+        case Nil  => typeName.short
+        case args => typeName.short + args.map(getName(annotations, _)).mkString
```
Comment (ghostdogpr) [inline core/src/main/scala/caliban/schema/Schema.scala:458]: I think you can pass an empty list for annotations, to avoid searching something that won’t be found.

Comment (kiranbayram) [reply core/src/main/scala/caliban/schema/Schema.scala]: good point 👍 updated.
