### PR TITLE
Fix for Issue 603

### LINKED ISSUE #603: Exception classes should override getMessage instead of toString
Exceptions sub classes overrides `toString` instead of `getMessage` for instance in https://github.com/ghostdogpr/caliban/blob/master/client/src/main/scala/caliban/client/CalibanClientError.scala#L13

As a result when these exceptions are logged through SLF4J, the stack trace does not contain the actual error message. For instance I get:

```
caliban.client.CalibanClientError$CommunicationError: null
	at caliban.client.SelectionBuilder.$anonfun$toRequestWithExtensions$2(SelectionBuilder.scala:95)
	at scala.util.Either$LeftProjection.map(Either.scala:573)
	at caliban.client.SelectionBuilder.$anonfun$toRequestWithExtensions$1(SelectionBuilder.scala:95)
        ...
```

I'll try to contribute a PR.

### PR DESCRIPTION
**Pull request by tdrozdowski**
Closes #603 - Added getMessage to CalibanClientError trait and implemented on Error classes; added spec for each implementation

### CODE REVIEW

File: client/src/main/scala/caliban/client/CalibanClientError.scala [hunk 1]
```diff
@@ -3,7 +3,10 @@ package caliban.client
 /**
  * The base type for all Caliban Client errors.
  */
-sealed trait CalibanClientError extends Throwable with Product with Serializable
+sealed trait CalibanClientError extends Throwable with Product with Serializable {
+  def msg: String
+  override def getMessage: String = msg
```
Comment (ghostdogpr) [inline client/src/main/scala/caliban/client/CalibanClientError.scala:8]: How about just `override def getMessage: String = toString`?

So we get the most details including for communication errors and decoding errors?

File: client/src/test/scala/caliban/client/CalibanClientErrorSpec.scala [hunk 2]
```diff
@@ -0,0 +1,41 @@
...
+          val graphQLResponseErrors = List(
+            GraphQLResponseError(
+              message = "Error1",
+              locations = Option(List(Location(line = 1, column = 1))),
+              path = Option(List(Left("somewhere"))),
+              extensions = Option.empty
+            )
+          )
+          val error = ServerError(graphQLResponseErrors)
+          assert(error.getMessage)(equalTo(error.toString))
```
Comment (ghostdogpr) [inline client/src/test/scala/caliban/client/CalibanClientErrorSpec.scala:36]: How checking the actual string here? To make sure the `toString` is producing what we expect? Otherwise you are just testing that `getMessage` points to `toString`.

File: client/src/main/scala/caliban/client/CalibanClientError.scala (hunk 1 above)
Comment (tdrozdowski) [reply client/src/main/scala/caliban/client/CalibanClientError.scala]: Done

File: client/src/test/scala/caliban/client/CalibanClientErrorSpec.scala (hunk 2 above)
Comment (tdrozdowski) [reply client/src/test/scala/caliban/client/CalibanClientErrorSpec.scala]: Done

File: client/src/test/scala/caliban/client/CalibanClientErrorSpec.scala [hunk 3]
```diff
@@ -0,0 +1,41 @@
...
+          val graphQLResponseErrors = List(
+            GraphQLResponseError(
+              message = "Error1",
+              locations = Option(List(Location(line = 1, column = 1))),
+              path = Option(List(Left("somewhere"))),
+              extensions = Option.empty
+            )
+          )
+          val error = ServerError(graphQLResponseErrors)
+          assert(error.getMessage)(equalTo("Server Error: Error1  at line 1 and column 1 at path /somewhere"))
```
Comment (ghostdogpr) [inline client/src/test/scala/caliban/client/CalibanClientErrorSpec.scala:36]: There's an extra space that can be fixed 😄  That test proved useful after all~

Comment (tdrozdowski) [reply client/src/test/scala/caliban/client/CalibanClientErrorSpec.scala:36]: The extra space due to processing the optional cause?

Comment (ghostdogpr) [reply client/src/test/scala/caliban/client/CalibanClientErrorSpec.scala:36]: I think it's the one between `${e.message} ${e.locations` that is not needed.

Comment (ghostdogpr) [reply client/src/test/scala/caliban/client/CalibanClientErrorSpec.scala:36]: Unless it's the one before "at". To be sure you could test one with 2 locations.

Comment (tdrozdowski) [reply client/src/test/scala/caliban/client/CalibanClientErrorSpec.scala]: Yeah, found it all - I think I have it now.

**Review by ghostdogpr — APPROVED** [review]
LGTM! Thank you!
