### PR TITLE
[Client] Add the option to drop null values from input objects

### LINKED ISSUE #778: Mutation contains null values if None is provided
Hi again,

after generating a schema and using it to connect a client to an existing GraphQL endpoint I stumbled over the following situation and I don't know if this is a bug or a feature and I just use it wrong. 

**Background:**
I generated a schema using graphQL introspection. As a result also the encoder `encode(value: T)` methods are generated in the schema class. 
When I now built a Mutation using this schema and don't provide data for all fields, the fields I don't provide data for stay `None` in scala. As a result, the created mutation, contains `null` values which leads to ` "Cannot convert undefined or null to object"` issues when executing the query. 

**Mutation Creation Code:**
```scala
    Mutation.createEntry(
      Some(EntryCreateInput(
        title = title,
        subTitle = subtitle,
        content = content,
        url = Some(url),
        `type` = Some(EntryTypeType.url),
        publishDate = Some(ZonedDateTime.now().toLocalDate.toString) // todo
      ))
    )(Entry.view()(CloudinaryImage_File.view(),
      Tag.view(Language.view, CloudinaryImage_File.view()),
      _QueryMeta.view,
      Language.view,
      Source.view(GeoLocation.view(LocationGoogle.view)))
    )
```

**Invalid Mutation:**
```
mutation {
  createEntry(
    data: {
      publishDate: null
      title: "<Dummy>"
      subTitle: "<Dummy>"
      image: null
      content: "<Dummy>"
      summary: null
      url: "<Dummy>"
      tags: null
      language: null
      source: null
      hasBeenTagged: null
      type: url
    }
  ) {...}
```

**Workaround/Solution:**
A workaround for us is to adapt the generated schema encoder by adding `.filterNot(_._2.equals(__NullValue))` after the generation of each list. 

**Resulting Valid Mutation:**
```
 mutation {
  createEntry(
    data: {
      title: "<Dummy>"
      subTitle: "<Dummy>"
      content: "<Dummy>"
      url: "<Dummy>"
      type: url
    }
  ) {...}
```

**Question:**
Do I just use the client mutation builder wrong or is this the intended behavior? Or is this also a bug?
If this is a bug, adding `.filterNot(_._2.equals(__NullValue))` in `ClientWriter:421` would fix this. 

Thanks in advance for any response.

### PR DESCRIPTION
**Pull request by ghostdogpr**
Closes #778

2 options: 
- pass `dropInputNullValues` when building the request to drop all of them
- pass a custom `ArgEncoder` when building the query to customize the behavior per input object type

### CODE REVIEW

File: client/src/main/scala/caliban/client/Selection.scala [hunk 1]
```diff
@@ -17,11 +17,12 @@ object Selection {
   case class Directive(name: String, arguments: List[Argument[_]] = Nil) {
     def toGraphQL(
       useVariables: Boolean,
+      dropInputNullValues: Boolean,
```
Comment (paulpdaniels) [inline client/src/main/scala/caliban/client/Selection.scala:20]: Nit: I think it would read better as `dropNullInputValues`

**Review by paulpdaniels — APPROVED** [review]

File: client/src/main/scala/caliban/client/Selection.scala (hunk 1 above)
Comment (ghostdogpr) [reply client/src/main/scala/caliban/client/Selection.scala]: Done~
