### PR TITLE
fix client writer using non-working suffix "_"

### LINKED ISSUE #775: Client Writer reservedKeywords check incomplete
Hi everyone,

first of all thanks for the library. I started working with it today and it has been very helpful so far. 

As I use gradle and not sbt for project builds, I manually had to add the `caliban-tools` to generate my schema class. After the generation the class did not compile, as our schema has a `_label_` field that interfers with the scala code syntax. The current implementation of `ClientWriter` converts the `_label_` to `def _label_:` which is not compiling. 

Short term workaround in our case is to just add `_label_` to `reservedKeywords` set in  `ClientWritter:628` in order to let `def _label_` become ``def `_label_`: `` which compiles seamlessly.

In the long run however I think it would make sense to have a proper check of a word starts or and with `_` in order to improve the code generation. 

If you're interested, I can hand in a PR for this within the next few days.

### PR DESCRIPTION
**Pull request by johanneshiry**
Resolves #775 

While working on the code, it turned out that `ClientWriter.safeUnapplyName()` also is affected and would require backticks. I added them accordingly.

If you require tests for these changes pls let me know.

### CODE REVIEW

**Comment by johanneshiry** [comment]
Cannot access the CI logs and hence don't know why the jdk_8 checks are failing =(

**Comment by ghostdogpr** [comment]
You can't access https://app.circleci.com/pipelines/github/ghostdogpr/caliban/2044/workflows/c6fa7b98-78c7-4209-a573-79648a617d96/jobs/8489 ? I thought it was public.

How about: https://circleci.com/api/v1.1/project/github/ghostdogpr/caliban/8489/output/103/0?file=true&allocation-id=603a4e85de77f412ac0ef069-0-build%2F7826A5FC

**Comment by johanneshiry** [comment]
First link requires a login to CircleCI (incl. account creation) - second link works. Thank you :)

**Comment by johanneshiry** [comment]
fixed the broken tests. However, I'm not totally happy with the solution as this now adds several (sometimes unnecessary) back ticks to variable/field names. The best and cleanest way would be to detect, if the fields are followed by `:` in order to only add back ticks in these cases. However, this would create several corner cases that need to be addressed then and hence would require several more changes. For the sake of minimal code changes, I would go with the solution proposed here anyway - even if I'm not totally happy with it. Depends on your opinion/review.

**Comment by ghostdogpr** [comment]
How about removing the final underscore and just use backticks? Having both seem weird.

The tests are still failing, this time it's the scripted test. You can see here the command ran by CircleCI: https://github.com/ghostdogpr/caliban/blob/ef74b0fcaefeba47cebf7f1f456cc3225ec48667/.circleci/config.yml#L24

**Comment by ghostdogpr** [comment]
Otherwise to minimize changes how about only adding backticks only when it *starts* with an underscore?

**Comment by johanneshiry** [comment]
taking your comments into account as well as experimenting a bit with it results in a totally different approach. I just replaced `_` with `$` and everything works like a charm - at least locally. Fingers crossed tests are passing ci as well 🤞🏼

**Comment by ghostdogpr** [comment]
Looking at the test code I think the backticks were better 😭 

Could we use $ instead of _ but keep the backticks in the other cases?

**Comment by johanneshiry** [comment]
sure thing - adapted the PR accordingly

File: tools/src/test/scala/caliban/tools/ClientWriterSpec.scala [hunk 1]
```diff
@@ -510,21 +510,21 @@ object Client {
     case object NEWHOPE extends Episode
     case object EMPIRE  extends Episode
     case object JEDI    extends Episode
-    case object jedi_   extends Episode
+    case object `jedi_` extends Episode
```
Comment (ghostdogpr) [inline tools/src/test/scala/caliban/tools/ClientWriterSpec.scala:513]: I wonder why there is still an underscore here, I would have expected `jedi`, no?

Comment (ghostdogpr) [reply tools/src/test/scala/caliban/tools/ClientWriterSpec.scala:513]: Ah it comes from `getMappingsClashedNames` adding underscores at the end which then triggers your new logic.
How about changing `getMappingsClashedNames` to use backticks instead? I think it would be nicer.

Comment (johanneshiry) [reply tools/src/test/scala/caliban/tools/ClientWriterSpec.scala:513]: Didn't know the exact place where you haven't been happy with the test code. And I agree, a Jedi definitely looks better with backticks instead of backticks and underscore. ;-)

**Review by ghostdogpr — APPROVED** [review]
LGTM! Thanks!

**Comment by ghostdogpr** [comment]
I realized only now that it introduced some warnings:
```
[info] [warn] /tmp/sbt_fd932119/src/main/scala/client/ClientGitLab.scala:147:17: Generated class client.ClientGitLab$AlertManagementAlertSort$UPDATED_DESC$ differs only in case from client.ClientGitLab$AlertManagementAlertSort$updated_desc$.
[info] [warn]   Such classes will overwrite one another on case-insensitive filesystems.
[info] [warn]     case object `UPDATED_DESC` extends AlertManagementAlertSort
[info] [warn]                 ^
[info] [warn] /tmp/sbt_fd932119/src/main/scala/client/ClientGitLab.scala:148:17: Generated class client.ClientGitLab$AlertManagementAlertSort$UPDATED_ASC$ differs only in case from client.ClientGitLab$AlertManagementAlertSort$updated_asc$.
[info] [warn]   Such classes will overwrite one another on case-insensitive filesystems.
[info] [warn]     case object `UPDATED_ASC` extends AlertManagementAlertSort
[info] [warn]                 ^
[info] [warn] /tmp/sbt_fd932119/src/main/scala/client/ClientGitLab.scala:149:17: Generated class client.ClientGitLab$AlertManagementAlertSort$CREATED_DESC$ differs only in case from client.ClientGitLab$AlertManagementAlertSort$created_desc$.
[info] [warn]   Such classes will overwrite one another on case-insensitive filesystems.
[info] [warn]     case object `CREATED_DESC` extends AlertManagementAlertSort
[info] [warn]                 ^
[info] [warn] /tmp/sbt_fd932119/src/main/scala/client/ClientGitLab.scala:150:17: Generated class client.ClientGitLab$AlertManagementAlertSort$CREATED_ASC$ differs only in case from client.ClientGitLab$AlertManagementAlertSort$created_asc$.
[info] [warn]   Such classes will overwrite one another on case-insensitive filesystems.
[info] [warn]     case object `CREATED_ASC` extends AlertManagementAlertSort
[info] [warn]                 ^
[info] [warn] /tmp/sbt_fd932119/src/main/scala/client/ClientGitLab.scala:1069:17: Generated class client.ClientGitLab$IssueSort$UPDATED_DESC$ differs only in case from client.ClientGitLab$IssueSort$updated_desc$.
[info] [warn]   Such classes will overwrite one another on case-insensitive filesystems.
[info] [warn]     case object `UPDATED_DESC` extends IssueSort
[info] [warn]                 ^
[info] [warn] /tmp/sbt_fd932119/src/main/scala/client/ClientGitLab.scala:1070:17: Generated class client.ClientGitLab$IssueSort$UPDATED_ASC$ differs only in case from client.ClientGitLab$IssueSort$updated_asc$.
[info] [warn]   Such classes will overwrite one another on case-insensitive filesystems.
[info] [warn]     case object `UPDATED_ASC` extends IssueSort
[info] [warn]                 ^
[info] [warn] /tmp/sbt_fd932119/src/main/scala/client/ClientGitLab.scala:1071:17: Generated class client.ClientGitLab$IssueSort$CREATED_DESC$ differs only in case from client.ClientGitLab$IssueSort$created_desc$.
[info] [warn]   Such classes will overwrite one another on case-insensitive filesystems.
[info] [warn]     case object `CREATED_DESC` extends IssueSort
[info] [warn]                 ^
[info] [warn] /tmp/sbt_fd932119/src/main/scala/client/ClientGitLab.scala:1072:17: Generated class client.ClientGitLab$IssueSort$CREATED_ASC$ differs only in case from client.ClientGitLab$IssueSort$created_asc$.
[info] [warn]   Such classes will overwrite one another on case-insensitive filesystems.
[info] [warn]     case object `CREATED_ASC` extends IssueSort
[info] [warn]                 ^
[info] [warn] /tmp/sbt_fd932119/src/main/scala/client/ClientGitLab.scala:1372:17: Generated class client.ClientGitLab$MergeRequestSort$UPDATED_DESC$ differs only in case from client.ClientGitLab$MergeRequestSort$updated_desc$.
[info] [warn]   Such classes will overwrite one another on case-insensitive filesystems.
[info] [warn]     case object `UPDATED_DESC` extends MergeRequestSort
[info] [warn]                 ^
[info] [warn] /tmp/sbt_fd932119/src/main/scala/client/ClientGitLab.scala:1373:17: Generated class client.ClientGitLab$MergeRequestSort$UPDATED_ASC$ differs only in case from client.ClientGitLab$MergeRequestSort$updated_asc$.
[info] [warn]   Such classes will overwrite one another on case-insensitive filesystems.
[info] [warn]     case object `UPDATED_ASC` extends MergeRequestSort
[info] [warn]                 ^
[info] [warn] /tmp/sbt_fd932119/src/main/scala/client/ClientGitLab.scala:1374:17: Generated class client.ClientGitLab$MergeRequestSort$CREATED_DESC$ differs only in case from client.ClientGitLab$MergeRequestSort$created_desc$.
[info] [warn]   Such classes will overwrite one another on case-insensitive filesystems.
[info] [warn]     case object `CREATED_DESC` extends MergeRequestSort
[info] [warn]                 ^
[info] [warn] /tmp/sbt_fd932119/src/main/scala/client/ClientGitLab.scala:1375:17: Generated class client.ClientGitLab$MergeRequestSort$CREATED_ASC$ differs only in case from client.ClientGitLab$MergeRequestSort$created_asc$.
[info] [warn]   Such classes will overwrite one another on case-insensitive filesystems.
[info] [warn]     case object `CREATED_ASC` extends MergeRequestSort
[info] [warn]                 ^
[info] [warn] /tmp/sbt_fd932119/src/main/scala/client/ClientGitLab.scala:2192:17: Generated class client.ClientGitLab$Sort$UPDATED_DESC$ differs only in case from client.ClientGitLab$Sort$updated_desc$.
[info] [warn]   Such classes will overwrite one another on case-insensitive filesystems.
[info] [warn]     case object `UPDATED_DESC` extends Sort
[info] [warn]                 ^
[info] [warn] /tmp/sbt_fd932119/src/main/scala/client/ClientGitLab.scala:2193:17: Generated class client.ClientGitLab$Sort$UPDATED_ASC$ differs only in case from client.ClientGitLab$Sort$updated_asc$.
[info] [warn]   Such classes will overwrite one another on case-insensitive filesystems.
[info] [warn]     case object `UPDATED_ASC` extends Sort
[info] [warn]                 ^
[info] [warn] /tmp/sbt_fd932119/src/main/scala/client/ClientGitLab.scala:2194:17: Generated class client.ClientGitLab$Sort$CREATED_DESC$ differs only in case from client.ClientGitLab$Sort$created_desc$.
[info] [warn]   Such classes will overwrite one another on case-insensitive filesystems.
[info] [warn]     case object `CREATED_DESC` extends Sort
[info] [warn]                 ^
[info] [warn] /tmp/sbt_fd932119/src/main/scala/client/ClientGitLab.scala:2195:17: Generated class client.ClientGitLab$Sort$CREATED_ASC$ differs only in case from client.ClientGitLab$Sort$created_asc$.
[info] [warn]   Such classes will overwrite one another on case-insensitive filesystems.
[info] [warn]     case object `CREATED_ASC` extends Sort
[info] [warn]                 ^
[info] [warn] /tmp/sbt_fd932119/src/main/scala/client/ClientNameUniqueness.scala:17:17: Generated class client.ClientNameUniqueness$Episode$jedi$ differs only in case from client.ClientNameUniqueness$Episode$JEDI$.
[info] [warn]   Such classes will overwrite one another on case-insensitive filesystems.
[info] [warn]     case object `jedi` extends Episode
[info] [warn]                 ^
[info] [warn] /tmp/sbt_fd932119/src/main/scala/client/ClientNameUniqueness.scala:51:10: Generated class client.ClientNameUniqueness$human$ differs only in case from client.ClientNameUniqueness$Human$.
[info] [warn]   Such classes will overwrite one another on case-insensitive filesystems.
[info] [warn]   object `human` {
[info] [warn]          ^
[info] [warn] /tmp/sbt_fd932119/src/main/scala/client/ClientNameUniqueness.scala:53:22: Generated class client.ClientNameUniqueness$human$humanView differs only in case from client.ClientNameUniqueness$Human$HumanView.
[info] [warn]   Such classes will overwrite one another on case-insensitive filesystems.
[info] [warn]     final case class humanView(name: String)
[info] [warn]                      ^
[info] [warn] /tmp/sbt_fd932119/src/main/scala/client/ClientNameUniqueness.scala:63:10: Generated class client.ClientNameUniqueness$humaN$ differs only in case from client.ClientNameUniqueness$Human$.
[info] [warn]   Such classes will overwrite one another on case-insensitive filesystems.
[info] [warn]   object `humaN` {
[info] [warn]          ^
[info] [warn] /tmp/sbt_fd932119/src/main/scala/client/ClientNameUniqueness.scala:65:22: Generated class client.ClientNameUniqueness$humaN$humaNView differs only in case from client.ClientNameUniqueness$Human$HumanView.
[info] [warn]   Such classes will overwrite one another on case-insensitive filesystems.
[info] [warn]     final case class humaNView(name: String)
[info] [warn]                      ^
[info] [warn] /tmp/sbt_fd932119/src/main/scala/client/ClientNameUniqueness.scala:131:14: Generated class client.ClientNameUniqueness$messageInput differs only in case from client.ClientNameUniqueness$MessageInput.
[info] [warn]   Such classes will overwrite one another on case-insensitive filesystems.
[info] [warn]   case class `messageInput`(
[info] [warn]              ^
[info] [warn] /tmp/sbt_fd932119/src/main/scala/client/ClientNameUniqueness.scala:135:10: Generated class client.ClientNameUniqueness$messageInput$ differs only in case from client.ClientNameUniqueness$MessageInput$.
[info] [warn]   Such classes will overwrite one another on case-insensitive filesystems.
[info] [warn]   object `messageInput` {
[info] [warn]          ^
[info] [warn] /tmp/sbt_fd932119/src/main/scala/client/ClientNameUniqueness.scala:152:14: Generated class client.ClientNameUniqueness$MessageInpuT differs only in case from client.ClientNameUniqueness$MessageInput.
[info] [warn]   Such classes will overwrite one another on case-insensitive filesystems.
[info] [warn]   case class `MessageInpuT`(
[info] [warn]              ^
[info] [warn] /tmp/sbt_fd932119/src/main/scala/client/ClientNameUniqueness.scala:156:10: Generated class client.ClientNameUniqueness$MessageInpuT$ differs only in case from client.ClientNameUniqueness$MessageInput$.
[info] [warn]   Such classes will overwrite one another on case-insensitive filesystems.
[info] [warn]   object `MessageInpuT` {
[info] [warn]          ^
[info] [warn] there were 8 deprecation warnings; re-run with -deprecation for details
[info] [warn] 26 warnings found
[info] [info] done compiling
```

Maybe we should use `$` for conflicts 🤔

**Comment by johanneshiry** [comment]
Can you describe how to reproduce this? I intended to work on the null filter at the coming weekend but might postpone it in order to fix this first. But would be helpful to know how to reproduce the issue. Or is this already in the main branch and I just missed the compiler warnings? 🤔 

Maybe you could re-open #775  again in order to trace this behavior there? :)

File: tools/src/main/scala/caliban/tools/ClientWriter.scala [hunk 2]
```diff
@@ -124,10 +125,9 @@ object ClientWriter {
       .map(name => name.toLowerCase -> name)
       .groupBy(_._1)
       .collect {
-        case (_, (_ :: typeNamesToRename)) if typeNamesToRename.nonEmpty =>
-          typeNamesToRename.zipWithIndex.map { case (((_, originalTypeName), index)) =>
-            val suffix = "_" * (index + 1)
-            originalTypeName -> s"$originalTypeName$suffix"
+        case (_, _ :: typeNamesToRename) if typeNamesToRename.nonEmpty =>
+          typeNamesToRename.map { case (_, originalTypeName) =>
+            originalTypeName -> s"`$originalTypeName`"
```
Comment (ghostdogpr) [inline tools/src/main/scala/caliban/tools/ClientWriter.scala:130]: Ah, the problem was here actually. The old logic was adding `_1`, `_2`, etc to discriminate names but the new logic isn't anymore. I will revert that part.

**Comment by ghostdogpr** [comment]
@johanneshiry I fixed it in https://github.com/ghostdogpr/caliban/pull/818 I introduced a suffix like `_1`, `_2`, etc to support more than 1 clashes. Since it doesn't end with underscore it shouldn't cause any problems.
