### PR TITLE
Fix Schema renaming on recursive types & Scala 3 nested union schema derivation

### LINKED ISSUE #1972: Scala 3 different schema derivation
The below produces different schemas depending on the Scala version:
```scala
@GQLName("ASTParameter")
sealed trait Parameter
object Parameter {
  implicit lazy val schema: Schema[Any, Parameter] = Schema.gen
}

@GQLName("ASTVariable")
case class Variable(name: String) extends Parameter
object Variable {
  implicit val schema: Schema[Any, Variable] = Schema.gen
}

@GQLName("ASTValue")
sealed trait Value extends Parameter
object Value {
  @GQLName("ASTValueBoolean")
  case class Boolean(value: scala.Boolean) extends Value
  object Boolean {
    implicit val schema: Schema[Any, Boolean] = Schema.gen
  }

  @GQLName("ASTValueList")
  case class List(values: Chunk[Value]) extends Value
  object List {
    implicit lazy val schema: Schema[Any, List] = Schema.gen
  }

  implicit lazy val schema: Schema[Any, Value] = Schema.gen
}

case class Queries(
  param: Parameter,
)
object Queries {
  implicit val schema: Schema[Any, Queries] = Schema.gen
}

val schema = {
  val queries = Queries(param = Variable("temp"))
  graphQL(RootResolver(queries))
}
```

Scala 2:
```graphql
schema {
  query: Queries
}

union ASTParameter = ASTValueBoolean | ASTValueList | ASTVariable

union ASTValue = ASTValueBoolean | ASTValueList

type ASTValueBoolean {
  value: Boolean!
}

type ASTValueList {
  values: [ASTValue!]!
}

type ASTVariable {
  name: String!
}

type Queries {
  param: ASTParameter!
}
```

Scala 3:
```graphql
schema {
  query: Queries
}

union ASTParameter = ASTValue | ASTVariable

union ASTValue = ASTValueBoolean | ASTValueList

type ASTValueBoolean {
  value: Boolean!
}

type ASTValueList {
  values: [ASTValue!]!
}

type ASTVariable {
  name: String!
}

type Queries {
  param: ASTParameter!
}
```

The Scala 3 schema is invalid due to having the union `ASTValue` as a member of the union `ASTParameter`.

### LINKED ISSUE #1973: `rename` fails when applied to derived recursive schema
```scala
sealed trait Parameter
object Parameter {
  implicit lazy val schema: Schema[Any, Parameter] = Schema.gen[Any, Parameter].rename("ASTParameter")
}

case class Variable(name: String) extends Parameter
object Variable {
  implicit val schema: Schema[Any, Variable] = Schema.gen[Any, Variable].rename("ASTVariable")
}

sealed trait Value extends Parameter
object Value {
  case class Boolean(value: scala.Boolean) extends Value
  object Boolean {
    implicit val schema: Schema[Any, Boolean] = Schema.gen[Any, Boolean].rename("ASTValueBoolean")
  }

  case class List(values: Chunk[Value]) extends Value
  object List {
    implicit lazy val schema: Schema[Any, List] = Schema.gen[Any, List].rename("ASTValueList")
  }

  implicit lazy val schema: Schema[Any, Value] = Schema.gen[Any, Value].rename("ASTValue")
}

case class Queries(
  param: Parameter,
)
object Queries {
  implicit val schema: Schema[Any, Queries] = Schema.gen
}

val schema = {
  val queries = Queries(param = Variable("temp"))
  graphQL(RootResolver(queries))
}
```

2.3.1
```graphql
schema {
  query: Queries
}

union ASTParameter = ASTValueBoolean | ASTValueList | ASTVariable

union ASTValue = ASTValueBoolean | ASTValueList

type ASTValueList {
  values: [ASTValue!]!
}

type ASTValueBoolean {
  value: Boolean!
}

type ASTVariable {
  name: String!
}

type Queries {
  param: ASTParameter!
}
```

2.4.1
```
[error] java.lang.StackOverflowError
[error] 	at magnolia1.CallByNeed.value(magnolia.scala:939)
[error] 	at magnolia1.Subtype$$anon$1.typeclass(interface.scala:74)
[error] 	at caliban.schema.CommonSchemaDerivation$$anon$2.$anonfun$toType$11(SchemaDerivation.scala:127)
[error] 	at scala.collection.immutable.ArraySeq.map(ArraySeq.scala:75)
[error] 	at scala.collection.immutable.ArraySeq.map(ArraySeq.scala:35)
[error] 	at caliban.schema.CommonSchemaDerivation$$anon$2.toType(SchemaDerivation.scala:127)
[error] 	at caliban.schema.Schema.caliban$schema$Schema$$asType(Schema.scala:40)
[error] 	at caliban.schema.Schema.caliban$schema$Schema$$asType$(Schema.scala:40)
[error] 	at caliban.schema.CommonSchemaDerivation$$anon$2.caliban$schema$Schema$$asType$lzycompute(SchemaDerivation.scala:123
[error] 	at caliban.schema.CommonSchemaDerivation$$anon$2.caliban$schema$Schema$$asType(SchemaDerivation.scala:123)
[error] 	at caliban.schema.Schema.toType_(Schema.scala:52)
[error] 	at caliban.schema.Schema.toType_$(Schema.scala:51)
[error] 	at caliban.schema.CommonSchemaDerivation$$anon$2.toType_(SchemaDerivation.scala:123)
[error] 	at caliban.schema.Schema$$anon$2.<init>(Schema.scala:118)
[error] 	at caliban.schema.Schema.rename(Schema.scala:110)
[error] 	at caliban.schema.Schema.rename$(Schema.scala:110)
[error] 	at caliban.schema.CommonSchemaDerivation$$anon$2.rename(SchemaDerivation.scala:123)
[error] 	at Test$Value$.schema$lzycompute(Test.scala:37)
[error] 	at Test$Value$.schema(Test.scala:37)
[error] 	at Test$Value$List$.schema$lzycompute(Test.scala:34)
[error] 	at Test$Value$List$.schema(Test.scala:34)
[error] 	at Test$Value$.$anonfun$schema$16(Test.scala:37)
[error] 	at magnolia1.CallByNeed.value$lzycompute(magnolia.scala:940)
[error] 	at magnolia1.CallByNeed.value(magnolia.scala:939)
                ... repeats
```
`Test.scala:34 = implicit lazy val schema: Schema[Any, List] = Schema.gen[Any, List].rename("ASTValueList")`
`Test.scala:37 = implicit lazy val schema: Schema[Any, Value] = Schema.gen[Any, Value].rename("ASTValue")`

On Scala 3, 2.4.1 hangs, 2.3.1 is fine.

I worked around it by adding `GQLName` annotations on the lazy schemas but if possible would be nice if it worked as before to avoid that module needing to depend on caliban.

### PR DESCRIPTION
**Pull request by kyri-petrou**
Closes #1972 by unpacking possibleTypes when creating union schemas for Scala 3. @ghostdogpr let me know if you agree with this approach, perhaps there's a simper / better one

Also closes #1973 which was caused by a regression in 2.4.0 where the `lazy val` was mistakenly changed to a `val`

### CODE REVIEW

File: core/src/main/scala/caliban/schema/Schema.scala [hunk 1]
```diff
@@ -105,7 +105,7 @@ trait Schema[-R, T] { self =>
       self.toType_(isInput, isSubscription).copy(name = Some(newName))
     }
 
-    private val renameTypename: Boolean = self.toType_().kind match {
+    private lazy val renameTypename: Boolean = self.toType_().kind match {
```
Comment (ghostdogpr) [inline core/src/main/scala/caliban/schema/Schema.scala:108]: Can you add the regression test for this?

Comment (kyri-petrou) [reply core/src/main/scala/caliban/schema/Schema.scala:108]: The test that I added was the repro for this fix. It just happens that the same test would also fail for the Scala 3 union issue, so I reused it

Comment (ghostdogpr) [reply core/src/main/scala/caliban/schema/Schema.scala:108]: Aha, okay. I just saw one so I thought it didn't cover both.
